### ISSUE TITLE
Release Version / Version on the Grafana marketplace

### ISSUE THREAD

**Issue by Daniel-Ebert** [snuids/grafana-trafficlights-panel#2]
Hi there,

many thanks for porting this to react! :) 
Do you already have an estimate when there will be a release package on github to be downloaded directly which I can place in my grafana plugins folder? 

Or when there will be a version on the Grafana marketplace?

Best regards

Daniel

**Comment by snuids** [comment]
Hi, The process has started. Hope it will be there in a few days. I am waiting for the signature.

Cheers,

Arnaud

**Comment by Daniel-Ebert** [comment]
Hi Arnaud,

great, thanks for your quick answer and your update! :)

Best regards

Daniel

**Comment by snuids** [comment]
It is live :-)

**Comment by Daniel-Ebert** [comment]
Perfect, thank you very much :) I must say I had to search for the package, I guess a github "Release" would have greater visibility ;) 
And will the plugin also come to the grafana marketplace soon, as you got it signed ? :)

**Comment by snuids** [comment]
<img width="981" alt="Screenshot 2024-06-06 at 17 28 28" src="https://github.com/snuids/grafana-trafficlights-panel/assets/13175107/51262021-2d8b-4e03-81f3-5778030a0980">

**Comment by snuids** [comment]
Should be there already

**Comment by Daniel-Ebert** [comment]
Ah great, thanks :)
